name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Create Artifact Registry Repository
        run: |
          gcloud artifacts repositories create nest-backend-repo \
            --repository-format=docker \
            --location=europe-west1 \
            --description="Docker repository for NestJS backend" \
            --quiet || echo "Repository already exists"
          
      - name: Docker Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Configure Docker
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet
          
      - name: Docker build and push
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nest-backend-repo/nest-app .
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nest-backend-repo/nest-app
            
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy nest-app \
            --image=europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nest-backend-repo/nest-app \
            --platform=managed \
            --region=europe-west1 \
            --allow-unauthenticated \
            --port=${{ secrets.PORT }}
        
