name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Docker build and push
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/nest-app .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nest-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy nest-app \
            --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/nest-app \
            --platform=managed \
            --region=europe-west1 \
            --allow-unauthenticated \
            --port=${{ secrets.PORT }} 
